services:
  # Define the backend Flask API service
  flask-app:
    build:
      context: .  # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      - MONGO_URI=mongodb://mongo:27017  # Connection string to MongoDB service
    depends_on:
      - mongo  # Ensure MongoDB starts before Flask app

  # Define the MongoDB service
  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

# Define named volumes for data persistence
volumes:
  mongo-data:
